[package]
name = "questionnaire"
description = "A library for creating a series of interactive questions for data gathering"
version = "0.0.1"
license = "Apache-2.0 OR MIT"
authors = ["SirWindfield <SirWindfield@users.noreply.github.com>"]
edition = "2018"

[dependencies]
