[workspace]
members = [
    "crates/checkbox",
    "crates/confirm",
    "crates/core",
    "crates/input",
    "crates/list",
    "crates/password",
    "crates/questionnaire",
    "crates/select"
]
